# Generated by Django 4.0.6 on 2023-04-17 20:19

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20230417_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechslerquestion',
            name='image',
            field=models.ImageField(default=None, upload_to=first_app.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechslerchild',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wechsler_test', to='first_app.childpersonalinfo'),
        ),
    ]
