# Generated by Django 4.0.6 on 2023-04-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_wechslerquestion_image_alter_wechslerchild_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechslerchild',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wechslerchild',
            name='father_name',
        ),
    ]
