# Generated by Django 4.0.6 on 2023-04-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_wechslerchild_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childinfoanswer',
            options={'verbose_name_plural': 'معلومات الطفل'},
        ),
        migrations.AlterModelOptions(
            name='childinfoblock',
            options={'verbose_name_plural': 'بلوكات معلومات الطفل'},
        ),
        migrations.AlterModelOptions(
            name='childinfoquestion',
            options={'verbose_name_plural': 'أسئلة معلومات الطفل'},
        ),
        migrations.AlterModelOptions(
            name='childpersonalinfo',
            options={'verbose_name_plural': 'الاطفال'},
        ),
        migrations.AlterModelOptions(
            name='lddrschild',
            options={'ordering': ['date'], 'verbose_name_plural': 'نتائج مقاييس التقدير التشخيصية'},
        ),
        migrations.AlterModelOptions(
            name='parentsblock',
            options={'verbose_name_plural': 'بلوكات اختبار الاهل'},
        ),
        migrations.AlterModelOptions(
            name='portageblock',
            options={'verbose_name_plural': 'بلوكات بورتيج'},
        ),
    ]
