# Generated by Django 4.0.6 on 2023-04-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_childinfoanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lddrsquestion',
            options={'verbose_name_plural': 'اسئلة مقاييس التقدير التشخيصية'},
        ),
        migrations.AlterModelOptions(
            name='lddrstest',
            options={'verbose_name_plural': 'اختبارات مقاييس التقدير التشخيصية'},
        ),
    ]
