# Generated by Django 4.0.6 on 2023-04-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_lddrsquestion_options_alter_lddrstest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechslerscaledscore',
            options={'verbose_name_plural': 'تثقيل اختبارات وكسلر'},
        ),
    ]
