# Generated by Django 4.0.6 on 2023-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_wechslerscaledscore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechslerchild',
            options={'verbose_name_plural': 'طفل وكسلر'},
        ),
    ]
