# Generated by Django 3.2 on 2023-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_wechslerchild_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpersonalinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
