# Generated by Django 4.0.6 on 2023-04-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_wechslerchild_birthdate_wechslerchild_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechslerchild',
            name='range',
        ),
        migrations.AlterField(
            model_name='wechslerchild',
            name='age',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
