# Generated by Django 4.0.6 on 2023-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_remove_wechslerchild_range_alter_wechslerchild_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechslerchild',
            name='range',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechslerchild',
            name='age',
            field=models.CharField(choices=[('7-4/7-7', '7-4/7-7'), ('5-1/5-5', '5-2/5-5')], max_length=20),
        ),
    ]
