# Generated by Django 4.0.6 on 2023-04-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_wechslerchild_range_alter_wechslerchild_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechslerchild',
            name='age',
        ),
        migrations.AlterField(
            model_name='wechslerchild',
            name='range',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
