# Generated by Django 4.0.6 on 2023-04-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_wechslerchild_age_alter_wechslerchild_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lddrstest',
            name='option',
        ),
    ]
