# Generated by Django 4.0.6 on 2023-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_remove_lddrstest_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='general_test',
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='test_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
