# Generated by Django 4.0.6 on 2023-04-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_remove_lddrsquestion_general_test_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LddrsTest',
        ),
    ]
