# Generated by Django 3.2 on 2023-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_delete_lddrstest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portagechildtest',
            old_name='level',
            new_name='diagnose',
        ),
        migrations.RenameField(
            model_name='portagechildtest',
            old_name='portage_test',
            new_name='test_name',
        ),
    ]
