# Generated by Django 3.2 on 2023-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20230507_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portagechildtest',
            name='diagnose',
            field=models.TextField(null=True),
        ),
    ]
