# Generated by Django 3.2 on 2023-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_alter_portagechildtest_diagnose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portagechildtest',
            name='diagnose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
