# Generated by Django 3.2 on 2023-05-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_alter_portagechildtest_diagnose'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAsweredPortageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_non_aswered_question', to='first_app.childpersonalinfo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_aswered_question_test', to='first_app.portagequestion')),
            ],
        ),
    ]
