# Generated by Django 3.2 on 2023-05-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_nonasweredportagequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonasweredportagequestion',
            name='test_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='non_aswered_question_test', to='first_app.portagetest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonasweredportagequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_aswered_question', to='first_app.portagequestion'),
        ),
    ]
