# Generated by Django 3.2 on 2023-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_auto_20230507_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='portagechildtest',
            name='treatment_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
