# Generated by Django 4.0.6 on 2023-05-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_auto_20230509_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lddrsquestion',
            old_name='question',
            new_name='diagnose',
        ),
        migrations.RemoveField(
            model_name='childpersonalinfo',
            name='Lddrs_diagnose_listening_difficulties',
        ),
        migrations.RemoveField(
            model_name='childpersonalinfo',
            name='Lddrs_diagnose_writing_difficulties',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='score',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='test_name',
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.childpersonalinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='test',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='treatment_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wechslerchild',
            name='treatment_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
