# Generated by Django 4.0.6 on 2023-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_rename_question_lddrsquestion_diagnose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lddrsquestion',
            old_name='diagnose',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='child',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='treatment_suggestion',
        ),
        migrations.AddField(
            model_name='lddrschild',
            name='treatment_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='score',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lddrsquestion',
            name='test_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
