# Generated by Django 4.0.6 on 2023-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_rename_diagnose_lddrsquestion_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childpersonalinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='childpersonalinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childpersonalinfo',
            name='full_name',
            field=models.CharField(default=None, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childpersonalinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
