# Generated by Django 4.0.6 on 2023-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0029_remove_childpersonalinfo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpersonalinfo',
            name='full_name',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
