# Generated by Django 4.0.6 on 2023-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Expert', 'Expert'), ('Parent', 'Parent')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
