# Generated by Django 3.2 on 2023-05-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_alter_account_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childpersonalinfo',
            old_name='age',
            new_name='age_years',
        ),
    ]
