# Generated by Django 3.2 on 2023-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0035_rename_age_years_childpersonalinfo_age_in_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpersonalinfo',
            name='age_in_days',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childpersonalinfo',
            name='age_in_months',
            field=models.IntegerField(default=None, editable=False),
            preserve_default=False,
        ),
    ]
