# Generated by Django 3.2 on 2023-05-11 21:07

from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0036_auto_20230511_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='', verbose_name=first_app.models.upload_to)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
