# Generated by Django 3.2 on 2023-05-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0039_auto_20230512_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='childpersonalinfo',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.account'),
        ),
    ]
