# Generated by Django 4.0.6 on 2023-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0040_childpersonalinfo_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutismAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Expert', 'Expert')], default='Expert', max_length=6),
        ),
        migrations.CreateModel(
            name='AutismQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesstion', models.TextField()),
                ('answer', models.ManyToManyField(to='first_app.autismanswer')),
            ],
        ),
    ]
