# Generated by Django 3.2 on 2023-05-18 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0041_autismanswer_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonasweredportagequestion',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_aswered_question_test', to='first_app.portagechildtest'),
        ),
    ]
