# Generated by Django 3.2 on 2023-05-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0042_alter_nonasweredportagequestion_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lddrsquestion',
            name='score',
        ),
    ]
