# Generated by Django 4.0.6 on 2023-05-20 16:16

from django.db import migrations, models
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0043_remove_lddrsquestion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechslerquestion',
            name='image',
            field=models.ImageField(blank=True, upload_to=first_app.models.upload_to),
        ),
    ]
