# Generated by Django 4.0.6 on 2023-05-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0045_alter_portagequestion_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portagequestion',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portage_qustions', to='first_app.portageblock'),
        ),
    ]
