# Generated by Django 4.0.6 on 2023-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0046_alter_portagequestion_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autismquestion',
            old_name='quesstion',
            new_name='question',
        ),
        migrations.AddField(
            model_name='autismquestion',
            name='age',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
