# Generated by Django 4.0.6 on 2023-05-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0047_rename_quesstion_autismquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autismquestion',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='first_app.autismanswer'),
        ),
    ]
