# Generated by Django 4.0.6 on 2023-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0049_wechslerchild_age_alter_autismquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lddrschild',
            name='age',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
