# Generated by Django 4.0.6 on 2023-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0050_lddrschild_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='lddrschild',
            name='birthdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
