# Generated by Django 4.0.6 on 2023-05-26 12:36

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0051_lddrschild_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyslexiaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('record', models.FileField(blank=True, null=True, upload_to=first_app.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='DyslexiaQuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=first_app.models.upload_to)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyslexia_images', to='first_app.dyslexiaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DyslexiaQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyslexia_answers', to='first_app.dyslexiaquestion')),
            ],
        ),
    ]
