# Generated by Django 4.0.6 on 2023-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0052_dyslexiaquestion_dyslexiaquestionimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portagechildtest',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
