# Generated by Django 4.0.6 on 2023-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0053_portagechildtest_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lddrschild',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
