# Generated by Django 4.0.6 on 2023-05-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0054_alter_lddrschild_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lddrschild',
            name='birthdate',
        ),
    ]
