# Generated by Django 4.0.6 on 2023-05-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0055_remove_lddrschild_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechslerchild',
            name='birthdate',
        ),
    ]
