# Generated by Django 4.0.6 on 2023-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0056_remove_wechslerchild_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechslerchild',
            name='birthdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
