# Generated by Django 4.0.6 on 2023-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0057_wechslerchild_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyslexiaquestionanswers',
            name='answer',
            field=models.TextField(),
        ),
    ]
