# Generated by Django 4.0.6 on 2023-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0058_alter_dyslexiaquestionanswers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyslexiaquestionanswers',
            name='answer',
            field=models.CharField(max_length=50),
        ),
    ]
