# Generated by Django 4.0.6 on 2023-05-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0060_alter_autismanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyslexiaquestion',
            name='hint',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
