# Generated by Django 3.2 on 2023-06-02 10:53

from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0062_alter_wechslerchild_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RavnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RavnQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(upload_to=first_app.models.upload_to)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='first_app.ravngroup')),
            ],
        ),
        migrations.CreateModel(
            name='RavnQuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=first_app.models.upload_to)),
                ('score', models.CharField(max_length=20)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asnwers', to='first_app.ravnquestion')),
            ],
        ),
    ]
