# Generated by Django 3.2 on 2023-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0064_alter_dyslexiaquestion_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyslexiaquestion',
            name='score',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyslexiaquestion',
            name='hint',
            field=models.CharField(max_length=40),
        ),
    ]
