# Generated by Django 3.2 on 2023-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0065_auto_20230602_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyslexiaquestion',
            name='score',
        ),
    ]
