# Generated by Django 3.2 on 2023-06-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0068_alter_dyslexiaquestion_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyslexiaquestion',
            name='score',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
