# Generated by Django 3.2 on 2023-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0069_dyslexiaquestion_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyslexiaquestion',
            name='score',
        ),
        migrations.AddField(
            model_name='dyslexiaquestionanswers',
            name='score',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
