# Generated by Django 3.2 on 2023-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0070_auto_20230604_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childpersonalinfo',
            name='child_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='childpersonalinfo',
            name='current_school',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
